services:
  - type: web
    name: line-fb-pusher
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - fromDotEnv: true

  - type: cron
    name: fbPush-daily
    env: node
    plan: free
    schedule: "0 0 * * *"  # 台灣時間早上 08:00（UTC+0）
    buildCommand: npm install
    startCommand: node fbPush.js
    envVars:
      - fromDotEnv: true
